### ISSUE TITLE
Не нужно делать очевидные комментарии (тем более на русском)

### ISSUE THREAD

**Issue by coursar** [aksiaaksi/HW2-wall_papers#1]
https://github.com/aksiaaksi/HW2-wall_papers/blob/8d8b785b015233b8c4ce7dce7a1a3fffdf6d077e/calculate_of_wallpaper.py#L25

**Comment by aksiaaksi** [comment]
См #1 
Исправлено 955a1b0ff56175b859d21166f07eaaaf5cc55051

**Comment by coursar** [comment]
1. Если исправили - закрывайте таску (не нужно её назначать на меня)
2. Не пишите в комментариях, в каком коммите закрыли - закрывайте сразу сообщениями коммиттов
