### ISSUE TITLE
Magic Constant: 0.1

### ISSUE THREAD

**Issue by coursar** [aksiaaksi/HW2-wall_papers#3]
Необходимо вынести в переменную и дать имя, по которой было бы понятно, что это такое.

https://github.com/aksiaaksi/HW2-wall_papers/blob/8d8b785b015233b8c4ce7dce7a1a3fffdf6d077e/calculate_of_wallpaper.py#L25

**Comment by aksiaaksi** [comment]
См #3
Исправил  955a1b0ff56175b859d21166f07eaaaf5cc55051
