### ISSUE TITLE
Почему бы сразу не назвать переменную safety_factor, а не f?

### ISSUE THREAD

**Issue by coursar** [aksiaaksi/HW2-wall_papers#4]
https://github.com/aksiaaksi/HW2-wall_papers/blob/997c97732cbcf8f8671117230cdd743204de814b/calculate_of_wallpaper.py#L13

**Comment by aksiaaksi** [comment]
См.#4
Исправлено f143f1f596a14f1949ee9755021af15ab39afc9c
